version: '3'

services:
  database:
    image: postgres
    restart: always
    command: "postgres -c max_connections=200"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=testtest
      - POSTGRES_DB=test
      - POSTGRES_HOST=test
    volumes:
      - database_post:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: "10mb"

  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: bash -c "python manage.py makemigrations core &&  python manage.py migrate && gunicorn SocialNetworkFriendsService.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=testtest
      - POSTGRES_DB=test
      - POSTGRES_HOST=database
      - DJANGO_SUPERUSER_USERNAME=admin2
      - DJANGO_SUPERUSER_PASSWORD=pass2
      - DJANGO_SUPERUSER_EMAIL=admin2@example.com
    volumes:
      - database_api:/app/core/migrations/
    depends_on:
      - database
    links:
      - database


volumes:
  database_post:
  database_api:


